//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace MTNCMWeb.SVC
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SendSmsBinding", Namespace = "http://www.csapi.org/wsdl/parlayx/sms/send/v2_2/service")]
    public partial class SendSmsService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        [XmlElement(Namespace = "http://www.huawei.com.cn/schema/common/v2_1")]
        public RequestSOAPHeader authCred;


        private System.Threading.SendOrPostCallback sendSmsOperationCompleted;

        private System.Threading.SendOrPostCallback sendSmsLogoOperationCompleted;

        private System.Threading.SendOrPostCallback sendSmsRingtoneOperationCompleted;

        private System.Threading.SendOrPostCallback getSmsDeliveryStatusOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public SendSmsService()
        {
            this.Url = string.Format(global::MTNCMWeb.Properties.Settings.Default.MTNCMWeb_SVC_SendSmsService, ((AppUtil.TestMode == 0) ? AppUtil.LiveIP : AppUtil.TestIP));
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event sendSmsCompletedEventHandler sendSmsCompleted;

        /// <remarks/>
        public event sendSmsLogoCompletedEventHandler sendSmsLogoCompleted;

        /// <remarks/>
        public event sendSmsRingtoneCompletedEventHandler sendSmsRingtoneCompleted;

        /// <remarks/>
        public event getSmsDeliveryStatusCompletedEventHandler getSmsDeliveryStatusCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeader("authCred", Direction = SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendSmsResponse", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
        public sendSmsResponse sendSms([System.Xml.Serialization.XmlElementAttribute("sendSms", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")] sendSms sendSms1)
        {
            object[] results = this.Invoke("sendSms", new object[] {
                        sendSms1});
            return ((sendSmsResponse)(results[0]));
        }

        /// <remarks/>
        public void sendSmsAsync(sendSms sendSms1)
        {
            this.sendSmsAsync(sendSms1, null);
        }

        /// <remarks/>
        public void sendSmsAsync(sendSms sendSms1, object userState)
        {
            if ((this.sendSmsOperationCompleted == null))
            {
                this.sendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsOperationCompleted);
            }
            this.InvokeAsync("sendSms", new object[] {
                        sendSms1}, this.sendSmsOperationCompleted, userState);
        }

        private void OnsendSmsOperationCompleted(object arg)
        {
            if ((this.sendSmsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsCompleted(this, new sendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendSmsLogoResponse", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
        public sendSmsLogoResponse sendSmsLogo([System.Xml.Serialization.XmlElementAttribute("sendSmsLogo", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")] sendSmsLogo sendSmsLogo1)
        {
            object[] results = this.Invoke("sendSmsLogo", new object[] {
                        sendSmsLogo1});
            return ((sendSmsLogoResponse)(results[0]));
        }

        /// <remarks/>
        public void sendSmsLogoAsync(sendSmsLogo sendSmsLogo1)
        {
            this.sendSmsLogoAsync(sendSmsLogo1, null);
        }

        /// <remarks/>
        public void sendSmsLogoAsync(sendSmsLogo sendSmsLogo1, object userState)
        {
            if ((this.sendSmsLogoOperationCompleted == null))
            {
                this.sendSmsLogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsLogoOperationCompleted);
            }
            this.InvokeAsync("sendSmsLogo", new object[] {
                        sendSmsLogo1}, this.sendSmsLogoOperationCompleted, userState);
        }

        private void OnsendSmsLogoOperationCompleted(object arg)
        {
            if ((this.sendSmsLogoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsLogoCompleted(this, new sendSmsLogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendSmsRingtoneResponse", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
        public sendSmsRingtoneResponse sendSmsRingtone([System.Xml.Serialization.XmlElementAttribute("sendSmsRingtone", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")] sendSmsRingtone sendSmsRingtone1)
        {
            object[] results = this.Invoke("sendSmsRingtone", new object[] {
                        sendSmsRingtone1});
            return ((sendSmsRingtoneResponse)(results[0]));
        }

        /// <remarks/>
        public void sendSmsRingtoneAsync(sendSmsRingtone sendSmsRingtone1)
        {
            this.sendSmsRingtoneAsync(sendSmsRingtone1, null);
        }

        /// <remarks/>
        public void sendSmsRingtoneAsync(sendSmsRingtone sendSmsRingtone1, object userState)
        {
            if ((this.sendSmsRingtoneOperationCompleted == null))
            {
                this.sendSmsRingtoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendSmsRingtoneOperationCompleted);
            }
            this.InvokeAsync("sendSmsRingtone", new object[] {
                        sendSmsRingtone1}, this.sendSmsRingtoneOperationCompleted, userState);
        }

        private void OnsendSmsRingtoneOperationCompleted(object arg)
        {
            if ((this.sendSmsRingtoneCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendSmsRingtoneCompleted(this, new sendSmsRingtoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getSmsDeliveryStatusResponse", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("result", IsNullable = false)]
        public DeliveryInformation[] getSmsDeliveryStatus([System.Xml.Serialization.XmlElementAttribute("getSmsDeliveryStatus", Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")] getSmsDeliveryStatus getSmsDeliveryStatus1)
        {
            object[] results = this.Invoke("getSmsDeliveryStatus", new object[] {
                        getSmsDeliveryStatus1});
            return ((DeliveryInformation[])(results[0]));
        }

        /// <remarks/>
        public void getSmsDeliveryStatusAsync(getSmsDeliveryStatus getSmsDeliveryStatus1)
        {
            this.getSmsDeliveryStatusAsync(getSmsDeliveryStatus1, null);
        }

        /// <remarks/>
        public void getSmsDeliveryStatusAsync(getSmsDeliveryStatus getSmsDeliveryStatus1, object userState)
        {
            if ((this.getSmsDeliveryStatusOperationCompleted == null))
            {
                this.getSmsDeliveryStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSmsDeliveryStatusOperationCompleted);
            }
            this.InvokeAsync("getSmsDeliveryStatus", new object[] {
                        getSmsDeliveryStatus1}, this.getSmsDeliveryStatusOperationCompleted, userState);
        }

        private void OngetSmsDeliveryStatusOperationCompleted(object arg)
        {
            if ((this.getSmsDeliveryStatusCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSmsDeliveryStatusCompleted(this, new getSmsDeliveryStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class sendSms
    {

        private string[] addressesField;

        private string senderNameField;

        private ChargingInformation chargingField;

        private string messageField;

        private SimpleReference receiptRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", DataType = "anyURI")]
        public string[] addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        public string senderName
        {
            get
            {
                return this.senderNameField;
            }
            set
            {
                this.senderNameField = value;
            }
        }

        /// <remarks/>
        public ChargingInformation charging
        {
            get
            {
                return this.chargingField;
            }
            set
            {
                this.chargingField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public SimpleReference receiptRequest
        {
            get
            {
                return this.receiptRequestField;
            }
            set
            {
                this.receiptRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/common/v2_1")]
    public partial class ChargingInformation
    {

        private string descriptionField;

        private string currencyField;

        private decimal amountField;

        private bool amountFieldSpecified;

        private string codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified
        {
            get
            {
                return this.amountFieldSpecified;
            }
            set
            {
                this.amountFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/v2_2")]
    public partial class DeliveryInformation
    {

        private string addressField;

        private DeliveryStatus deliveryStatusField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeliveryStatus deliveryStatus
        {
            get
            {
                return this.deliveryStatusField;
            }
            set
            {
                this.deliveryStatusField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/v2_2")]
    public enum DeliveryStatus
    {

        /// <remarks/>
        DeliveredToNetwork,

        /// <remarks/>
        DeliveryUncertain,

        /// <remarks/>
        DeliveryImpossible,

        /// <remarks/>
        MessageWaiting,

        /// <remarks/>
        DeliveredToTerminal,

        /// <remarks/>
        DeliveryNotificationNotSupported,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class getSmsDeliveryStatus
    {

        private string requestIdentifierField;

        /// <remarks/>
        public string requestIdentifier
        {
            get
            {
                return this.requestIdentifierField;
            }
            set
            {
                this.requestIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class sendSmsRingtoneResponse
    {

        private string resultField;

        /// <remarks/>
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class sendSmsRingtone
    {

        private string[] addressesField;

        private string senderNameField;

        private ChargingInformation chargingField;

        private string ringtoneField;

        private SmsFormat smsFormatField;

        private SimpleReference receiptRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", DataType = "anyURI")]
        public string[] addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        public string senderName
        {
            get
            {
                return this.senderNameField;
            }
            set
            {
                this.senderNameField = value;
            }
        }

        /// <remarks/>
        public ChargingInformation charging
        {
            get
            {
                return this.chargingField;
            }
            set
            {
                this.chargingField = value;
            }
        }

        /// <remarks/>
        public string ringtone
        {
            get
            {
                return this.ringtoneField;
            }
            set
            {
                this.ringtoneField = value;
            }
        }

        /// <remarks/>
        public SmsFormat smsFormat
        {
            get
            {
                return this.smsFormatField;
            }
            set
            {
                this.smsFormatField = value;
            }
        }

        /// <remarks/>
        public SimpleReference receiptRequest
        {
            get
            {
                return this.receiptRequestField;
            }
            set
            {
                this.receiptRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/v2_2")]
    public enum SmsFormat
    {

        /// <remarks/>
        Ems,

        /// <remarks/>
        SmartMessaging,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/common/v2_1")]
    public partial class SimpleReference
    {

        private string endpointField;

        private string interfaceNameField;

        private string correlatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public string endpoint
        {
            get
            {
                return this.endpointField;
            }
            set
            {
                this.endpointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string interfaceName
        {
            get
            {
                return this.interfaceNameField;
            }
            set
            {
                this.interfaceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correlator
        {
            get
            {
                return this.correlatorField;
            }
            set
            {
                this.correlatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class sendSmsLogoResponse
    {

        private string resultField;

        /// <remarks/>
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class sendSmsLogo
    {

        private string[] addressesField;

        private string senderNameField;

        private ChargingInformation chargingField;

        private byte[] imageField;

        private SmsFormat smsFormatField;

        private SimpleReference receiptRequestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("addresses", DataType = "anyURI")]
        public string[] addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }

        /// <remarks/>
        public string senderName
        {
            get
            {
                return this.senderNameField;
            }
            set
            {
                this.senderNameField = value;
            }
        }

        /// <remarks/>
        public ChargingInformation charging
        {
            get
            {
                return this.chargingField;
            }
            set
            {
                this.chargingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }

        /// <remarks/>
        public SmsFormat smsFormat
        {
            get
            {
                return this.smsFormatField;
            }
            set
            {
                this.smsFormatField = value;
            }
        }

        /// <remarks/>
        public SimpleReference receiptRequest
        {
            get
            {
                return this.receiptRequestField;
            }
            set
            {
                this.receiptRequestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.csapi.org/schema/parlayx/sms/send/v2_2/local")]
    public partial class sendSmsResponse
    {

        private string resultField;

        /// <remarks/>
        public string result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void sendSmsCompletedEventHandler(object sender, sendSmsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal sendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public sendSmsResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((sendSmsResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void sendSmsLogoCompletedEventHandler(object sender, sendSmsLogoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsLogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal sendSmsLogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public sendSmsLogoResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((sendSmsLogoResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void sendSmsRingtoneCompletedEventHandler(object sender, sendSmsRingtoneCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendSmsRingtoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal sendSmsRingtoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public sendSmsRingtoneResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((sendSmsRingtoneResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getSmsDeliveryStatusCompletedEventHandler(object sender, getSmsDeliveryStatusCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSmsDeliveryStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getSmsDeliveryStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public DeliveryInformation[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((DeliveryInformation[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591