//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTNSAWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncOrderRelationResponse
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Timestamped { get; set; }
        public string Result { get; set; }
        public string ResultDescription { get; set; }
        public string ResultInterpretation { get; set; }
        public Nullable<int> SyncOrderRelationExtendedID { get; set; }
    
        public virtual SyncOrderRelationExtended SyncOrderRelationExtended { get; set; }
    }
}
