//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace MTNNSub.SUBVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SubscribeManageBinding", Namespace="http://www.csapi.org/wsdl/parlayx/subscribe/manage/v1_0/service")]
    public partial class SubscribeManageService : System.Web.Services.Protocols.SoapHttpClientProtocol {

        [XmlElement(Namespace = "http://www.huawei.com.cn/schema/common/v2_1")]
        public RequestSOAPHeader authCred;

        
        private System.Threading.SendOrPostCallback subscribeServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback unSubscribeServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback subscribeProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback unSubscribeProductOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SubscribeManageService() {
            this.Url = string.Format(global::MTNNSub.Properties.Settings.Default.MTNNSub_SUBVC_SubscribeManageService, ((AppUtil.TestMode == 0) ? AppUtil.LiveIP : AppUtil.TestIP));
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event subscribeServiceCompletedEventHandler subscribeServiceCompleted;
        
        /// <remarks/>
        public event unSubscribeServiceCompletedEventHandler unSubscribeServiceCompleted;
        
        /// <remarks/>
        public event subscribeProductCompletedEventHandler subscribeProductCompleted;
        
        /// <remarks/>
        public event unSubscribeProductCompletedEventHandler unSubscribeProductCompleted;
        
        /// <remarks/>
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("subscribeServiceResponse", Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
        public subscribeServiceResponse subscribeService([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")] subscribeServiceRequest subscribeServiceRequest) {
            object[] results = this.Invoke("subscribeService", new object[] {
                        subscribeServiceRequest});
            return ((subscribeServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void subscribeServiceAsync(subscribeServiceRequest subscribeServiceRequest) {
            this.subscribeServiceAsync(subscribeServiceRequest, null);
        }
        
        /// <remarks/>
        public void subscribeServiceAsync(subscribeServiceRequest subscribeServiceRequest, object userState) {
            if ((this.subscribeServiceOperationCompleted == null)) {
                this.subscribeServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubscribeServiceOperationCompleted);
            }
            this.InvokeAsync("subscribeService", new object[] {
                        subscribeServiceRequest}, this.subscribeServiceOperationCompleted, userState);
        }
        
        private void OnsubscribeServiceOperationCompleted(object arg) {
            if ((this.subscribeServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.subscribeServiceCompleted(this, new subscribeServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("unSubscribeServiceResponse", Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
        public unSubscribeServiceResponse unSubscribeService([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")] unSubscribeServiceRequest unSubscribeServiceRequest) {
            object[] results = this.Invoke("unSubscribeService", new object[] {
                        unSubscribeServiceRequest});
            return ((unSubscribeServiceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void unSubscribeServiceAsync(unSubscribeServiceRequest unSubscribeServiceRequest) {
            this.unSubscribeServiceAsync(unSubscribeServiceRequest, null);
        }
        
        /// <remarks/>
        public void unSubscribeServiceAsync(unSubscribeServiceRequest unSubscribeServiceRequest, object userState) {
            if ((this.unSubscribeServiceOperationCompleted == null)) {
                this.unSubscribeServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunSubscribeServiceOperationCompleted);
            }
            this.InvokeAsync("unSubscribeService", new object[] {
                        unSubscribeServiceRequest}, this.unSubscribeServiceOperationCompleted, userState);
        }
        
        private void OnunSubscribeServiceOperationCompleted(object arg) {
            if ((this.unSubscribeServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unSubscribeServiceCompleted(this, new unSubscribeServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeader("authCred", Direction = SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("subscribeProductResponse", Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
        public subscribeProductResponse subscribeProduct([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")] subscribeProductRequest subscribeProductRequest) {
            object[] results = this.Invoke("subscribeProduct", new object[] {
                        subscribeProductRequest});
            return ((subscribeProductResponse)(results[0]));
        }
        
        /// <remarks/>
        public void subscribeProductAsync(subscribeProductRequest subscribeProductRequest) {
            this.subscribeProductAsync(subscribeProductRequest, null);
        }
        
        /// <remarks/>
        public void subscribeProductAsync(subscribeProductRequest subscribeProductRequest, object userState) {
            if ((this.subscribeProductOperationCompleted == null)) {
                this.subscribeProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsubscribeProductOperationCompleted);
            }
            this.InvokeAsync("subscribeProduct", new object[] {
                        subscribeProductRequest}, this.subscribeProductOperationCompleted, userState);
        }
        
        private void OnsubscribeProductOperationCompleted(object arg) {
            if ((this.subscribeProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.subscribeProductCompleted(this, new subscribeProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeader("authCred", Direction = SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("unSubscribeProductResponse", Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
        public unSubscribeProductResponse unSubscribeProduct([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")] unSubscribeProductRequest unSubscribeProductRequest) {
            object[] results = this.Invoke("unSubscribeProduct", new object[] {
                        unSubscribeProductRequest});
            return ((unSubscribeProductResponse)(results[0]));
        }
        
        /// <remarks/>
        public void unSubscribeProductAsync(unSubscribeProductRequest unSubscribeProductRequest) {
            this.unSubscribeProductAsync(unSubscribeProductRequest, null);
        }
        
        /// <remarks/>
        public void unSubscribeProductAsync(unSubscribeProductRequest unSubscribeProductRequest, object userState) {
            if ((this.unSubscribeProductOperationCompleted == null)) {
                this.unSubscribeProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnunSubscribeProductOperationCompleted);
            }
            this.InvokeAsync("unSubscribeProduct", new object[] {
                        unSubscribeProductRequest}, this.unSubscribeProductOperationCompleted, userState);
        }
        
        private void OnunSubscribeProductOperationCompleted(object arg) {
            if ((this.unSubscribeProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.unSubscribeProductCompleted(this, new unSubscribeProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class subscribeServiceRequest {
        
        private SubscribeServiceReq subscribeServiceReqField;
        
        /// <remarks/>
        public SubscribeServiceReq subscribeServiceReq {
            get {
                return this.subscribeServiceReqField;
            }
            set {
                this.subscribeServiceReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class SubscribeServiceReq {
        
        private string userIdField;
        
        private string productIdField;
        
        private string operatorField;
        
        private int operatorTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int operatorType {
            get {
                return this.operatorTypeField;
            }
            set {
                this.operatorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class UnSubscribeProductRsp {
        
        private string resultField;
        
        private string resultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class unSubscribeProductResponse {
        
        private UnSubscribeProductRsp unSubscribeProductRspField;
        
        /// <remarks/>
        public UnSubscribeProductRsp unSubscribeProductRsp {
            get {
                return this.unSubscribeProductRspField;
            }
            set {
                this.unSubscribeProductRspField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class UnSubscribeProductReq {
        
        private UserID userIDField;
        
        private SubInfo subInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UserID userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SubInfo subInfo {
            get {
                return this.subInfoField;
            }
            set {
                this.subInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class UserID {
        
        private string idField;
        
        private int typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class SubInfo {
        
        private string productIDField;
        
        private string operCodeField;
        
        private int isAutoExtendField;
        
        private bool isAutoExtendFieldSpecified;
        
        private int channelIDField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operCode {
            get {
                return this.operCodeField;
            }
            set {
                this.operCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int isAutoExtend {
            get {
                return this.isAutoExtendField;
            }
            set {
                this.isAutoExtendField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAutoExtendSpecified {
            get {
                return this.isAutoExtendFieldSpecified;
            }
            set {
                this.isAutoExtendFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int channelID {
            get {
                return this.channelIDField;
            }
            set {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("namedParameters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class NamedParameter {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class unSubscribeProductRequest {
        
        private UnSubscribeProductReq unSubscribeProductReqField;
        
        /// <remarks/>
        public UnSubscribeProductReq unSubscribeProductReq {
            get {
                return this.unSubscribeProductReqField;
            }
            set {
                this.unSubscribeProductReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class SubscribeProductRsp {
        
        private string resultField;
        
        private string resultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class subscribeProductResponse {
        
        private SubscribeProductRsp subscribeProductRspField;
        
        /// <remarks/>
        public SubscribeProductRsp subscribeProductRsp {
            get {
                return this.subscribeProductRspField;
            }
            set {
                this.subscribeProductRspField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class SubscribeProductReq {
        
        private UserID userIDField;
        
        private SubInfo subInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UserID userID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SubInfo subInfo {
            get {
                return this.subInfoField;
            }
            set {
                this.subInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class subscribeProductRequest {
        
        private SubscribeProductReq subscribeProductReqField;
        
        /// <remarks/>
        public SubscribeProductReq subscribeProductReq {
            get {
                return this.subscribeProductReqField;
            }
            set {
                this.subscribeProductReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class UnSubscribeServiceRsp {
        
        private int resultCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class unSubscribeServiceResponse {
        
        private UnSubscribeServiceRsp unSubscribeServiceRspField;
        
        /// <remarks/>
        public UnSubscribeServiceRsp unSubscribeServiceRsp {
            get {
                return this.unSubscribeServiceRspField;
            }
            set {
                this.unSubscribeServiceRspField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class UnSubscribeServiceReq {
        
        private string userIdField;
        
        private string productIdField;
        
        private string operatorField;
        
        private int operatorTypeField;
        
        private int reasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int operatorType {
            get {
                return this.operatorTypeField;
            }
            set {
                this.operatorTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class unSubscribeServiceRequest {
        
        private UnSubscribeServiceReq unSubscribeServiceReqField;
        
        /// <remarks/>
        public UnSubscribeServiceReq unSubscribeServiceReq {
            get {
                return this.unSubscribeServiceReqField;
            }
            set {
                this.unSubscribeServiceReqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/v1_0")]
    public partial class SubscribeServiceRsp {
        
        private int resultCodeField;
        
        private string mSISDNField;
        
        private string spIdField;
        
        private string serviceIdField;
        
        private int subscriptionConflictNumField;
        
        private string subscriptionConflictTypesField;
        
        private string subscriptionConflictSpIdsField;
        
        private string subscriptionConflictServiceIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSISDN {
            get {
                return this.mSISDNField;
            }
            set {
                this.mSISDNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string spId {
            get {
                return this.spIdField;
            }
            set {
                this.spIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int subscriptionConflictNum {
            get {
                return this.subscriptionConflictNumField;
            }
            set {
                this.subscriptionConflictNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subscriptionConflictTypes {
            get {
                return this.subscriptionConflictTypesField;
            }
            set {
                this.subscriptionConflictTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subscriptionConflictSpIds {
            get {
                return this.subscriptionConflictSpIdsField;
            }
            set {
                this.subscriptionConflictSpIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subscriptionConflictServiceIds {
            get {
                return this.subscriptionConflictServiceIdsField;
            }
            set {
                this.subscriptionConflictServiceIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/subscribe/manage/v1_0/local")]
    public partial class subscribeServiceResponse {
        
        private SubscribeServiceRsp subscribeServiceRspField;
        
        /// <remarks/>
        public SubscribeServiceRsp subscribeServiceRsp {
            get {
                return this.subscribeServiceRspField;
            }
            set {
                this.subscribeServiceRspField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void subscribeServiceCompletedEventHandler(object sender, subscribeServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class subscribeServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal subscribeServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public subscribeServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((subscribeServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void unSubscribeServiceCompletedEventHandler(object sender, unSubscribeServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unSubscribeServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unSubscribeServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public unSubscribeServiceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((unSubscribeServiceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void subscribeProductCompletedEventHandler(object sender, subscribeProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class subscribeProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal subscribeProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public subscribeProductResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((subscribeProductResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void unSubscribeProductCompletedEventHandler(object sender, unSubscribeProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class unSubscribeProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal unSubscribeProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public unSubscribeProductResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((unSubscribeProductResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591