//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTNCInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncOrderError
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Cause { get; set; }
    }
}
