//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTNCInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncOrderRelation
    {
        public SyncOrderRelation()
        {
            this.SyncOrderRelationExtendeds = new HashSet<SyncOrderRelationExtended>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> Timestamped { get; set; }
        public string UserID { get; set; }
        public Nullable<int> UserType { get; set; }
        public string ServiceProviderID { get; set; }
        public string ProductID { get; set; }
        public string ServiceID { get; set; }
        public string ServiceList { get; set; }
        public Nullable<int> UpdateType { get; set; }
        public string UpdateTime { get; set; }
        public string UpdateDescription { get; set; }
        public string EffectiveTime { get; set; }
        public string ExpiryTime { get; set; }
        public Nullable<int> Passed { get; set; }
    
        public virtual ICollection<SyncOrderRelationExtended> SyncOrderRelationExtendeds { get; set; }
    }
}
