//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTNNSub
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLog
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> Timestamped { get; set; }
    }
}
