//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace MTNCInfo.AUTHSVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="authorizationBinding", Namespace="http://www.csapi.org/wsdl/authorization/service/v1_0")]
    public partial class authorizationService : System.Web.Services.Protocols.SoapHttpClientProtocol {

        [XmlElement(Namespace = "http://www.huawei.com.cn/schema/common/v2_1")]
        public RequestSOAPHeader authCred;

        private RequestSOAPHeader requestSOAPHeaderValueField;
        
        private System.Threading.SendOrPostCallback authorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateAuthorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAuthorizationOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryAuthorizationListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public authorizationService() {
            this.Url = string.Format(global::MTNCInfo.Properties.Settings.Default.MTNNWeb_AUTHSVC_authorizationService, ((AppUtil.TestMode == 0) ? AppUtil.LiveIP : AppUtil.TestIP));
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestSOAPHeader RequestSOAPHeaderValue {
            get {
                return this.requestSOAPHeaderValueField;
            }
            set {
                this.requestSOAPHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event authorizationCompletedEventHandler authorizationCompleted;
        
        /// <remarks/>
        public event updateAuthorizationCompletedEventHandler updateAuthorizationCompleted;
        
        /// <remarks/>
        public event queryAuthorizationCompletedEventHandler queryAuthorizationCompleted;
        
        /// <remarks/>
        public event queryAuthorizationListCompletedEventHandler queryAuthorizationListCompleted;
        
        /// <remarks/>
        //[System.Web.Services.Protocols.SoapHeaderAttribute("RequestSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapHeader("authCred", Direction = SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("authorizationResponse", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
        public AuthorizationResponse authorization([System.Xml.Serialization.XmlElementAttribute("authorization", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")] Authorization authorization1) {
            object[] results = this.Invoke("authorization", new object[] {
                        authorization1});
            return ((AuthorizationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void authorizationAsync(Authorization authorization1) {
            this.authorizationAsync(authorization1, null);
        }
        
        /// <remarks/>
        public void authorizationAsync(Authorization authorization1, object userState) {
            if ((this.authorizationOperationCompleted == null)) {
                this.authorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthorizationOperationCompleted);
            }
            this.InvokeAsync("authorization", new object[] {
                        authorization1}, this.authorizationOperationCompleted, userState);
        }
        
        private void OnauthorizationOperationCompleted(object arg) {
            if ((this.authorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authorizationCompleted(this, new authorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateAuthorizationResponse", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
        public UpdateAuthorizationResponse updateAuthorization([System.Xml.Serialization.XmlElementAttribute("updateAuthorization", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")] UpdateAuthorization updateAuthorization1) {
            object[] results = this.Invoke("updateAuthorization", new object[] {
                        updateAuthorization1});
            return ((UpdateAuthorizationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateAuthorizationAsync(UpdateAuthorization updateAuthorization1) {
            this.updateAuthorizationAsync(updateAuthorization1, null);
        }
        
        /// <remarks/>
        public void updateAuthorizationAsync(UpdateAuthorization updateAuthorization1, object userState) {
            if ((this.updateAuthorizationOperationCompleted == null)) {
                this.updateAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateAuthorizationOperationCompleted);
            }
            this.InvokeAsync("updateAuthorization", new object[] {
                        updateAuthorization1}, this.updateAuthorizationOperationCompleted, userState);
        }
        
        private void OnupdateAuthorizationOperationCompleted(object arg) {
            if ((this.updateAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateAuthorizationCompleted(this, new updateAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryAuthorizationResponse", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
        public QueryAuthorizationResponse queryAuthorization([System.Xml.Serialization.XmlElementAttribute("queryAuthorization", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")] QueryAuthorization queryAuthorization1) {
            object[] results = this.Invoke("queryAuthorization", new object[] {
                        queryAuthorization1});
            return ((QueryAuthorizationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryAuthorizationAsync(QueryAuthorization queryAuthorization1) {
            this.queryAuthorizationAsync(queryAuthorization1, null);
        }
        
        /// <remarks/>
        public void queryAuthorizationAsync(QueryAuthorization queryAuthorization1, object userState) {
            if ((this.queryAuthorizationOperationCompleted == null)) {
                this.queryAuthorizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAuthorizationOperationCompleted);
            }
            this.InvokeAsync("queryAuthorization", new object[] {
                        queryAuthorization1}, this.queryAuthorizationOperationCompleted, userState);
        }
        
        private void OnqueryAuthorizationOperationCompleted(object arg) {
            if ((this.queryAuthorizationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAuthorizationCompleted(this, new queryAuthorizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestSOAPHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("queryAuthorizationListResponse", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
        public QueryAuthorizationListResponse queryAuthorizationList([System.Xml.Serialization.XmlElementAttribute("queryAuthorizationList", Namespace="http://www.csapi.org/schema/authorization/local/v1_0")] QueryAuthorizationList queryAuthorizationList1) {
            object[] results = this.Invoke("queryAuthorizationList", new object[] {
                        queryAuthorizationList1});
            return ((QueryAuthorizationListResponse)(results[0]));
        }
        
        /// <remarks/>
        public void queryAuthorizationListAsync(QueryAuthorizationList queryAuthorizationList1) {
            this.queryAuthorizationListAsync(queryAuthorizationList1, null);
        }
        
        /// <remarks/>
        public void queryAuthorizationListAsync(QueryAuthorizationList queryAuthorizationList1, object userState) {
            if ((this.queryAuthorizationListOperationCompleted == null)) {
                this.queryAuthorizationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryAuthorizationListOperationCompleted);
            }
            this.InvokeAsync("queryAuthorizationList", new object[] {
                        queryAuthorizationList1}, this.queryAuthorizationListOperationCompleted, userState);
        }
        
        private void OnqueryAuthorizationListOperationCompleted(object arg) {
            if ((this.queryAuthorizationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryAuthorizationListCompleted(this, new queryAuthorizationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.huawei.com.cn/schema/common/v2_1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.huawei.com.cn/schema/common/v2_1", IsNullable=false)]
    public partial class RequestSOAPHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string spIdField;
        
        private string spPasswordField;
        
        private string timeStampField;

        private string serviceIdField;
        
        /// <remarks/>
        public string spId {
            get {
                return this.spIdField;
            }
            set {
                this.spIdField = value;
            }
        }
        
        /// <remarks/>
        public string spPassword {
            get {
                return this.spPasswordField;
            }
            set {
                this.spPasswordField = value;
            }
        }

        public string serviceId { get { return this.serviceIdField; } set { this.serviceIdField = value; } }

        /// <remarks/>
        public string timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/data/v1_0")]
    public partial class DetailedAuthorizationInfo {
        
        private string productNameField;
        
        private string productIdField;
        
        private string transactionIdField;
        
        private int amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string serviceIntervalField;
        
        private string serviceIntervalUnitField;
        
        private string accessTokenStatusField;
        
        private string accessTokenField;
        
        private string tokenValidityField;
        
        private int tokenCategoryField;
        
        private bool tokenCategoryFieldSpecified;
        
        private string authorizationtypeField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceInterval {
            get {
                return this.serviceIntervalField;
            }
            set {
                this.serviceIntervalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string serviceIntervalUnit {
            get {
                return this.serviceIntervalUnitField;
            }
            set {
                this.serviceIntervalUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accessTokenStatus {
            get {
                return this.accessTokenStatusField;
            }
            set {
                this.accessTokenStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenValidity {
            get {
                return this.tokenValidityField;
            }
            set {
                this.tokenValidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tokenCategory {
            get {
                return this.tokenCategoryField;
            }
            set {
                this.tokenCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tokenCategorySpecified {
            get {
                return this.tokenCategoryFieldSpecified;
            }
            set {
                this.tokenCategoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorizationtype {
            get {
                return this.authorizationtypeField;
            }
            set {
                this.authorizationtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/data/v1_0")]
    public partial class NamedParameter {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class QueryAuthorizationListResponse {
        
        private Result resultField;
        
        private DetailedAuthorizationInfo[] authorizationInfoListField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("detailedAuthorizationInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DetailedAuthorizationInfo[] authorizationInfoList {
            get {
                return this.authorizationInfoListField;
            }
            set {
                this.authorizationInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/data/v1_0")]
    public partial class Result {
        
        private string resultCodeField;
        
        private string resultDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class QueryAuthorizationList {
        
        private string endUserIdentifierField;
        
        private string operationField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public string endUserIdentifier {
            get {
                return this.endUserIdentifierField;
            }
            set {
                this.endUserIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/data/v1_0")]
    public partial class BriefAuthorizationInfo {
        
        private string accessTokenStatusField;
        
        private string accessTokenField;
        
        private string tokenValidityField;
        
        private int totalAmountField;
        
        private bool totalAmountFieldSpecified;
        
        private string authorizationtypeField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accessTokenStatus {
            get {
                return this.accessTokenStatusField;
            }
            set {
                this.accessTokenStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenValidity {
            get {
                return this.tokenValidityField;
            }
            set {
                this.tokenValidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int totalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalAmountSpecified {
            get {
                return this.totalAmountFieldSpecified;
            }
            set {
                this.totalAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorizationtype {
            get {
                return this.authorizationtypeField;
            }
            set {
                this.authorizationtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class QueryAuthorizationResponse {
        
        private Result resultField;
        
        private BriefAuthorizationInfo authorizationInfoField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public BriefAuthorizationInfo authorizationInfo {
            get {
                return this.authorizationInfoField;
            }
            set {
                this.authorizationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class QueryAuthorization {
        
        private string endUserIdentifierField;
        
        private string transactionIdField;
        
        private string accessTokenField;
        
        private string serviceIdField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public string endUserIdentifier {
            get {
                return this.endUserIdentifierField;
            }
            set {
                this.endUserIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="UpdateAuthorization", Namespace="http://www.csapi.org/schema/authorization/data/v1_0")]
    public partial class UpdateAuthorization1 {
        
        private string productIdField;
        
        private string accessTokenField;
        
        private string authorizationtypeField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string accessToken {
            get {
                return this.accessTokenField;
            }
            set {
                this.accessTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorizationtype {
            get {
                return this.authorizationtypeField;
            }
            set {
                this.authorizationtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class UpdateAuthorizationResponse {
        
        private Result resultField;
        
        private UpdateAuthorization1 updateAuthorizationField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public UpdateAuthorization1 updateAuthorization {
            get {
                return this.updateAuthorizationField;
            }
            set {
                this.updateAuthorizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class UpdateAuthorization {
        
        private string endUserIdentifierField;
        
        private string transactionIdField;
        
        private string operationField;
        
        private string notificationEventRequiredField;
        
        private string authorizationtypeField;
        
        private string productIdField;
        
        private string needSMSConfirmField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public string endUserIdentifier {
            get {
                return this.endUserIdentifierField;
            }
            set {
                this.endUserIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
            }
        }
        
        /// <remarks/>
        public string notificationEventRequired {
            get {
                return this.notificationEventRequiredField;
            }
            set {
                this.notificationEventRequiredField = value;
            }
        }
        
        /// <remarks/>
        public string authorizationtype {
            get {
                return this.authorizationtypeField;
            }
            set {
                this.authorizationtypeField = value;
            }
        }
        
        /// <remarks/>
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        public string needSMSConfirm {
            get {
                return this.needSMSConfirmField;
            }
            set {
                this.needSMSConfirmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class AuthorizationResponse {
        
        private Result resultField;
        
        private string tokenField;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/authorization/local/v1_0")]
    public partial class Authorization {
        
        private string endUserIdentifierField;
        
        private string transactionIdField;
        
        private string scopeField;
        
        private string serviceIdField;
        
        private long amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string contentIdField;
        
        private string frequencyField;
        
        private string descriptionField;
        
        private string notificationURLField;
        
        private long tokenValidityField;
        
        private bool tokenValidityFieldSpecified;
        
        private NamedParameter[] extensionInfoField;
        
        /// <remarks/>
        public string endUserIdentifier {
            get {
                return this.endUserIdentifierField;
            }
            set {
                this.endUserIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        public string serviceId {
            get {
                return this.serviceIdField;
            }
            set {
                this.serviceIdField = value;
            }
        }
        
        /// <remarks/>
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string contentId {
            get {
                return this.contentIdField;
            }
            set {
                this.contentIdField = value;
            }
        }
        
        /// <remarks/>
        public string frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string notificationURL {
            get {
                return this.notificationURLField;
            }
            set {
                this.notificationURLField = value;
            }
        }
        
        /// <remarks/>
        public long tokenValidity {
            get {
                return this.tokenValidityField;
            }
            set {
                this.tokenValidityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tokenValiditySpecified {
            get {
                return this.tokenValidityFieldSpecified;
            }
            set {
                this.tokenValidityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public NamedParameter[] extensionInfo {
            get {
                return this.extensionInfoField;
            }
            set {
                this.extensionInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void authorizationCompletedEventHandler(object sender, authorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthorizationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthorizationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateAuthorizationCompletedEventHandler(object sender, updateAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateAuthorizationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateAuthorizationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void queryAuthorizationCompletedEventHandler(object sender, queryAuthorizationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAuthorizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAuthorizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryAuthorizationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryAuthorizationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void queryAuthorizationListCompletedEventHandler(object sender, queryAuthorizationListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryAuthorizationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryAuthorizationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public QueryAuthorizationListResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((QueryAuthorizationListResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591