//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.0.
// 
#pragma warning disable 1591

namespace MTNCChat.NSDSVC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmsNotificationBinding", Namespace="http://www.csapi.org/wsdl/parlayx/sms/notification/v2_2/service")]
    public partial class SmsNotificationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback notifySmsReceptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback notifySmsDeliveryReceiptOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SmsNotificationService() {
            this.Url = string.Format(global::MTNCChat.Properties.Settings.Default.MTNCChat_NSDSVS_SmsNotificationService, ((AppUtil.TestMode == 0) ? AppUtil.LiveIP : AppUtil.TestIP));
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event notifySmsReceptionCompletedEventHandler notifySmsReceptionCompleted;
        
        /// <remarks/>
        public event notifySmsDeliveryReceiptCompletedEventHandler notifySmsDeliveryReceiptCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("notifySmsReceptionResponse", Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")]
        public notifySmsReceptionResponse notifySmsReception([System.Xml.Serialization.XmlElementAttribute("notifySmsReception", Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")] notifySmsReception notifySmsReception1) {
            object[] results = this.Invoke("notifySmsReception", new object[] {
                        notifySmsReception1});
            return ((notifySmsReceptionResponse)(results[0]));
        }
        
        /// <remarks/>
        public void notifySmsReceptionAsync(notifySmsReception notifySmsReception1) {
            this.notifySmsReceptionAsync(notifySmsReception1, null);
        }
        
        /// <remarks/>
        public void notifySmsReceptionAsync(notifySmsReception notifySmsReception1, object userState) {
            if ((this.notifySmsReceptionOperationCompleted == null)) {
                this.notifySmsReceptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnotifySmsReceptionOperationCompleted);
            }
            this.InvokeAsync("notifySmsReception", new object[] {
                        notifySmsReception1}, this.notifySmsReceptionOperationCompleted, userState);
        }
        
        private void OnnotifySmsReceptionOperationCompleted(object arg) {
            if ((this.notifySmsReceptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.notifySmsReceptionCompleted(this, new notifySmsReceptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("notifySmsDeliveryReceiptResponse", Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")]
        public notifySmsDeliveryReceiptResponse notifySmsDeliveryReceipt([System.Xml.Serialization.XmlElementAttribute("notifySmsDeliveryReceipt", Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")] notifySmsDeliveryReceipt notifySmsDeliveryReceipt1) {
            object[] results = this.Invoke("notifySmsDeliveryReceipt", new object[] {
                        notifySmsDeliveryReceipt1});
            return ((notifySmsDeliveryReceiptResponse)(results[0]));
        }
        
        /// <remarks/>
        public void notifySmsDeliveryReceiptAsync(notifySmsDeliveryReceipt notifySmsDeliveryReceipt1) {
            this.notifySmsDeliveryReceiptAsync(notifySmsDeliveryReceipt1, null);
        }
        
        /// <remarks/>
        public void notifySmsDeliveryReceiptAsync(notifySmsDeliveryReceipt notifySmsDeliveryReceipt1, object userState) {
            if ((this.notifySmsDeliveryReceiptOperationCompleted == null)) {
                this.notifySmsDeliveryReceiptOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnotifySmsDeliveryReceiptOperationCompleted);
            }
            this.InvokeAsync("notifySmsDeliveryReceipt", new object[] {
                        notifySmsDeliveryReceipt1}, this.notifySmsDeliveryReceiptOperationCompleted, userState);
        }
        
        private void OnnotifySmsDeliveryReceiptOperationCompleted(object arg) {
            if ((this.notifySmsDeliveryReceiptCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.notifySmsDeliveryReceiptCompleted(this, new notifySmsDeliveryReceiptCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")]
    public partial class notifySmsReception {
        
        private string correlatorField;
        
        private SmsMessage messageField;
        
        /// <remarks/>
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
        
        /// <remarks/>
        public SmsMessage message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v2_2")]
    public partial class SmsMessage {
        
        private string messageField;
        
        private string senderAddressField;
        
        private string smsServiceActivationNumberField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string senderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                this.senderAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string smsServiceActivationNumber {
            get {
                return this.smsServiceActivationNumberField;
            }
            set {
                this.smsServiceActivationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")]
    public partial class notifySmsDeliveryReceiptResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v2_2")]
    public partial class DeliveryInformation {
        
        private string addressField;
        
        private DeliveryStatus deliveryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI")]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DeliveryStatus deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/v2_2")]
    public enum DeliveryStatus {
        
        /// <remarks/>
        DeliveredToNetwork,
        
        /// <remarks/>
        DeliveryUncertain,
        
        /// <remarks/>
        DeliveryImpossible,
        
        /// <remarks/>
        MessageWaiting,
        
        /// <remarks/>
        DeliveredToTerminal,
        
        /// <remarks/>
        DeliveryNotificationNotSupported,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")]
    public partial class notifySmsDeliveryReceipt {
        
        private string correlatorField;
        
        private DeliveryInformation deliveryStatusField;
        
        /// <remarks/>
        public string correlator {
            get {
                return this.correlatorField;
            }
            set {
                this.correlatorField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryInformation deliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.57.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.csapi.org/schema/parlayx/sms/notification/v2_2/local")]
    public partial class notifySmsReceptionResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void notifySmsReceptionCompletedEventHandler(object sender, notifySmsReceptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class notifySmsReceptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal notifySmsReceptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public notifySmsReceptionResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((notifySmsReceptionResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    public delegate void notifySmsDeliveryReceiptCompletedEventHandler(object sender, notifySmsDeliveryReceiptCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.57.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class notifySmsDeliveryReceiptCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal notifySmsDeliveryReceiptCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public notifySmsDeliveryReceiptResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((notifySmsDeliveryReceiptResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591